version: "3"

services:
    nginx:
        image: nginx
        restart: always
        depends_on: 
        - api
        environment:
        - VUE_APP_API_ENDPOINT='http://localhost/api'
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./dist2:/app
        ports:
        - "80:80"
    api:
        image: food
        restart: always
        expose:
        - "5000"

