version: "3"

services:
  delivery.nginx:
    image: delivery.nginx:dev
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - delivery.api
    environment:
      - NODE_ENV=development
      - VUE_APP_API_ENDPOINT="http://localhost"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
  delivery.api:
    image: delivery.api:dev
    build:
      context: ./back-end
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    expose:
      - "5000"

